# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20171015_1143'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
