# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introductory_text', models.TextField()),
                ('single_option_text', models.TextField()),
                ('multiple_option_text', models.TextField()),
                ('preferred_day_set_text', models.TextField()),
                ('default_reply_text', models.TextField()),
            ],
        ),
    ]
