# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='no_option_text',
            field=models.TextField(null=True),
        ),
    ]
