# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_preferences_no_option_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='day_pattern_matching',
            field=models.TextField(null=True),
        ),
    ]
