# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
