# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_preferred_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
