# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_timeframe',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='meterage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='preferred_day',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
    ]
