# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='flag',
            field=models.NullBooleanField(default=False),
        ),
    ]
