# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20171014_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='description',
            new_name='text',
        ),
    ]
