# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_flags_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flags',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flags',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
