# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20171016_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flags',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
