# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_invoiced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoiced',
            field=models.NullBooleanField(default=False),
        ),
    ]
